# Site settings
title: Kirisky
email: youandox@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Record my interest and experience. Code for fun!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kirisky.github.com" # the base hostname & protocol for your site
author: kirisky
twitter_username: jekyllrb
github_username:  kirisky
githuburl:	https://github.com/kirisky
footer: this is my personal blog

# Build settings
markdown: kramdown

# Post paginate
paginate: 20

# Markdown
highlighter: true
safe: true